version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True